### ISSUE TITLE
INVALID_INDEX problem

### ISSUE THREAD

**Issue by mirecc414** [abellgithub/delaunator-cpp#20]
Hello,
I don't have any other means to contact you, so I resorted to creating new issue. I am trying to figure out what am I doing wrong - I have ~1000 points defined and I am trying to run triangulation on them. Then i am iterating halfedges for some further processing but some of them are pointing to "INVALID_INDEX" (std::numeric_limits<std::size_t>::max()). It occours close the end of halfedges vector. What can cause this behavior? Positions of points that I am feeding into Delaunator are in magnitude of 100-s.

Thanks in advance and sorry for this form of contact.

![image](https://github.com/abellgithub/delaunator-cpp/assets/13500265/faf73731-f7c1-446a-b57e-285c92d8ff3a)

**Comment by abellgithub** [comment]
I haven't looked at this code in a long time, but I think that if you have an invalid index, it means that the edge is on the outside of the triangulation (there is no triangle on the other side of the edge). If you want to provide the data and code you're using I can take a look.

**Comment by mirecc414** [comment]
Thanks, It makes a lot of sense to me now, I wonder how i didn't see it.
I tried to run super simple example from your READ ME: 
```
std::vector<double> coords = { -1, 1, 1, 1, 1, -1, -1, -1 };
delaunator::Delaunator del = delaunator::Delaunator(coords);
```
results look like this
![image](https://github.com/abellgithub/delaunator-cpp/assets/13500265/92f46430-3a61-4973-889d-2e52277d0875)
