### ISSUE TITLE
Tagged version?

### ISSUE THREAD

**Issue by cerati** [abellgithub/delaunator-cpp#24]
It seems to me the original `delfrrr/delaunator-cpp` repo is not being developed anymore and this is where the actual developments are taking place. However, I do not see tags or releases in this repository. Is there a stable version people should use? Thanks

**Comment by cerati** [comment]
Thanks for your prompt reply. I ended up here because I was using the original repo and there was a infinite loop in the legalize function which is fixed in this repo. Our software stack includes ~150 packages, which are typically managed based on tags. However it looks like we can also use commit hashes, so I can just take the last commit as reference as use it. I can close the issue.

**Comment by abellgithub** [comment]
Done.

**Comment by cerati** [comment]
Thank you @abellgithub !
