### ISSUE TITLE
Logic error in bounding rectangle initialization.

### ISSUE THREAD

**Issue by MK-3PP** [abellgithub/delaunator-cpp#6]
std::numeric_limits<double>::min() is used to initialize maximum value variables that should grow to the highest encountered value. It represents the smallest positive normal double, so this value can never grow negative (e. g. for only negative inputs). Use std::numeric_limits<double>::lowest() istead.

Lines 199 and 200 of delaunator.cpp:
`double max_x = (std::numeric_limits<double>::min)();`
`double max_y = (std::numeric_limits<double>::min)();`

should be:
`double max_x = std::numeric_limits<double>::lowest();`
`double max_y = std::numeric_limits<double>::lowest();`

**Comment by abellgithub** [comment]
Fixed with bf1ea6d82948a07759a4c1086e8b8b841f99b60e
